# Generated by Django 4.2.5 on 2025-06-19 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0007_profile_where_active_friendship'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='date_time',
            new_name='sent_at',
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administered_group', to='reg.profile'),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/group_avatars'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attached_image',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/messages'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(max_length=4096),
        ),
    ]
