# Generated by Django 4.2.5 on 2025-06-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0007_profile_where_active_friendship'),
        ('chat', '0002_rename_date_time_chatmessage_sent_at_chatgroup_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='imgs/group_avatars')),
                ('members', models.ManyToManyField(to='reg.profile')),
            ],
        ),
    ]
