# Generated by Django 4.2.5 on 2025-06-12 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reg', '0004_profile_messages_profile_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='reg.profile')),
                ('to_who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='reg.profile')),
            ],
            options={
                'unique_together': {('from_who', 'to_who')},
            },
        ),
    ]
