# Generated by Django 5.1 on 2025-05-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationcodes',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
