# Generated by Django 4.2.5 on 2025-06-12 07:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reg', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='messages',
            field=models.ManyToManyField(default=0, related_name='msgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='requests',
            field=models.ManyToManyField(default=0, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
