# Generated by Django 4.2.5 on 2025-06-12 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0004_profile_messages_profile_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='requests',
        ),
    ]
