# Generated by Django 4.2.5 on 2025-06-19 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='where_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FriendShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('profile1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_sent_request', to='reg.profile')),
                ('profile2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_accepted_request', to='reg.profile')),
            ],
        ),
    ]
