# Generated by Django 4.2.17 on 2025-05-18 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_publications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_post',
            old_name='name',
            new_name='title',
        ),
    ]
