# Generated by Django 4.2.5 on 2025-06-15 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0006_alter_profile_image'),
        ('my_publications', '0003_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.profile'),
        ),
    ]
