# Generated by Django 4.2.5 on 2025-06-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_album_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='album',
            name='topic',
            field=models.CharField(choices=[('nature', 'Природа'), ('travel', 'Подорож'), ('art', 'Мистецтво')], default='nature', max_length=50),
        ),
        migrations.AddField(
            model_name='album',
            name='year',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
